### ISSUE TITLE
Ability to set projectId on the dataSource

### ISSUE THREAD

**Issue by Stono** [GoogleCloudPlatform/cloud-logging-data-source-plugin#43]
Hi, 
It'd be great if i could select the projectId on the datasource during provisioning.  For context; we run a grafana instance per environment, each environment for us (eg testing, dev, preprod, prod, bcp) is also a separate GCP project.

Ta

**Comment by xiangshen-dk** [comment]
You should be able to use the [plugin config file](https://grafana.com/docs/grafana/latest/administration/provisioning/#config-file) to specify the default project.

Below is an example:

sudo cat /etc/grafana/provisioning/datasources/logging.yaml

```yaml
# # config file version
apiVersion: 1

datasources:
  - name: Google Cloud Logging
    type: googlecloud-logging-datasource
    access: proxy
    editable: true
    jsonData:
      #authenticationType: gce
      #gceDefaultProject: shenxiang-gcp-solutions-test1
      authenticationType: jwt
      defaultProject: shenxiang-gcp-solution
      ClientEmail: "grafana-test@shenxiang-gcp-solution.iam.gserviceaccount.com"
    secureJsonData:
      privateKey: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADA.........X+q2g=\n-----END PRIVATE KEY-----\n"
```
