### ISSUE TITLE
Support local gcloud default credentials

### ISSUE THREAD

**Issue by Stono** [GoogleCloudPlatform/cloud-logging-data-source-plugin#44]
I'm struggling to run grafana locally and use this data source.  Ideally i'd like it to use my gcloud auth default credentials.  The two configuration options at the moment look to be json (which i want to avoid) and gce (which isn't relevant locally).

It'd be great if this just transparently worked, like gcloud client libraries.

**Comment by xiangshen-dk** [comment]
You can try to specify the auth type as gce in the configuration file. As you can see in the [code](https://github.com/GoogleCloudPlatform/cloud-logging-data-source-plugin/blob/main/pkg/plugin/plugin.go#L114), for gce auth the plugin uses application default credentials with client library. 

Below is an example of the config file:

sudo cat /etc/grafana/provisioning/datasources/logging.yaml

```yaml
# # config file version
apiVersion: 1

datasources:
  - name: Google Cloud Logging
    type: googlecloud-logging-datasource
    access: proxy
    editable: true
    jsonData:
      authenticationType: gce
      gceDefaultProject: shenxiang-gcp-solutions-test1
```
