### ISSUE TITLE
Plugin ID When installing through Grafana provisioning

### ISSUE THREAD

**Issue by laetho** [GoogleCloudPlatform/cloud-logging-data-source-plugin#56]
I'm trying to install the Google Cloud Logging plugin through the provisioning mechanisms in Grafana. But the plugin id (used in type:) does not resolve or is not what the documentation tells me it is (googlecloud-logging-datasource).

Below is my configuration and it works for monitoring and trace, but logging gives me an error indicating it cannot find the plugin id corresponding to the 'type: googlecloud-logging-datasource'

```yaml
apiVersion: 1

deleteDatasources:
  - name: Google Cloud Monitoring
  - name: Google Cloud Trace
  - name: Google Cloud Logging

datasources:
  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    jsonData:
      authenticationType: gce
  - name: Google Cloud Trace
    type: googlecloud-trace-datasource
    access: proxy
    jsonData:
      authenticationType: gce
  - name: Google Cloud Logging
    type: googlecloud-logging-datasource
    access: proxy
    jsonData:
      authenticationType: gce
```

Is the plugin id just wrong here or do I need to look elsewhere?
